package models
{
	import controllers.FileIOController;
	
	import flash.filesystem.File;

	/**
	 * Represents a file generated by the Aerial Framework
	 */
	public class GeneratedFile
	{
		public static const PHP_BASE_MODEL:String = "phpBaseModel";
		public static const PHP_MODEL:String = "phpModel";
		public static const PHP_SERVICE:String = "phpService";
		public static const AS3_MODEL:String = "as3Model";
		public static const AS3_SERVICE:String = "as3Service";
		
		private var _type:String;
		
		public var path:File;
		public var content:String;
		
		public function GeneratedFile(type:String)
		{
			this._type = type;
		}
		
		public function readContent(path:File=null):void
		{
			if(path)
				this.path = path;
			
			if(!this.path || !this.path.exists)
				throw new Error("Cannot read file from non-existent path");
				
			this.content = FileIOController.read(this.path, false, String) as String;
		}
		
		public function writeContent(path:File):void
		{
			if(path)
				this.path = path;
			
			if(!this.path)
				throw new Error("Cannot write file to null path");
			
			if(!this.content || this.content.length == 0)
				throw new Error("Cannot write null content");
			
			FileIOController.write(this.path, this.content, true, String);
		}
	}
}